const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ACCREDITATION_ADMIN: 'ACCREDITATION_ADMIN',
  FACULTY_REVIEWER: 'FACULTY_REVIEWER',
  PROJECT_COORDINATOR: 'PROJECT_COORDINATOR',
  STUDENT: 'STUDENT',
  VIEWER: 'VIEWER',
};

// Roles allowed to make final review decisions on evidence.
const REVIEWER_ROLES = [ROLES.FACULTY_REVIEWER, ROLES.ACCREDITATION_ADMIN, ROLES.SUPER_ADMIN];

// Roles allowed to administer users/system.
const ADMIN_ROLES = [ROLES.SUPER_ADMIN, ROLES.ACCREDITATION_ADMIN];

module.exports = { ROLES, REVIEWER_ROLES, ADMIN_ROLES };
